### ISSUE TITLE
OMG Issue 17074: BaseMaintenanceService.updateChangeableMetadata parameters

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#11]
http://www.omg.org/issues/cts2-ftf.html#Issue17074

Add effectiveDate, changeNotes, changeSource parameters, all optional.  Used to update ChangeDescription if supported by the service

**Comment by kevinpeterson** [comment]
In the spec, the method is currently:

```
updateChangeableMetadata(changeSet:ChangeSetURI, entryID:PersistentURI, status:NameOrURI, entryState:EntryState)
```

How would a user remove the 'Status' - for example? This also comes into play when we add in the optional parameters above. Does passing in null mean 'don't updated' or 'set to null'?

This also applies, I believe, to the 'updateChangeSetMetadata' method.

**Comment by hsolbrig** [comment]
status is marked as "OPT" in the specification meaning that the API needs to support three possibilities:  No change, Delete or Update/Add.  The best pattern that we've been able to identify in these circumstances that OPT parameters have one additional array wrapper - the updateChangeableMetadata signature would mark status as array(NameOrURI) (NameOrURI[]) in Java).  Null would mean don't change, [] would mean delete and [element] would mean change.  ([element1, element2] would be considered an error for single value parameters.

Multiple occurrence parameters would follow the same pattern - while we considered an individual addElement/removeElement signature, it was complex enough that we decided that the client needs to replace the entire array.

**Comment by kevinpeterson** [comment]
### Reason For Change

The attributes 'effectiveDate', 'changeNotes', and 'changeSource' of a 'Changeable' need to be able to be updated.

### Severity: Minor

### Proposed Resolution (PIM)

Updated Diagram (Figure 3.7: Maintenace Service. Core, Page 56.)
![Figure 3.7: Maintenace Service. Core, Page 56.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/04/MaintenanceService.jpg)

### Proposed Resolution (PSM)

Add 'effectiveDate', 'changeNotes', and 'changeSource' elements to 'UpdateChangeableMetadataRequest.'

#### Change Location: CoreService.xsd

#### Description

Add in the following elements to the type 'UpdateChangeableMetadataRequest':

``` xml
<xs:element name="updatedEffectiveDate" minOccurs="0">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="effectiveDate" type="core:DateAndTime" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="updatedChangeNotes" minOccurs="0">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="changeNotes" type="core:OpaqueData" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="updatedChangeSource" minOccurs="0">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="changeSource" type="core:SourceReference" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
```

### Updated XML

``` xml
<xs:element name="UpdateChangeableMetadataRequest" type="UpdateChangeableMetadataRequest"/>
<xs:complexType name="UpdateChangeableMetadataRequest">
    <xs:sequence>
        <xs:element name="updatedStatus" minOccurs="0"> 
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="status" type="NameOrURI" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="updatedEntryState" minOccurs="0">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="entryState" type="core:EntryState"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
---Start-Added--->
        <xs:element name="updatedEffectiveDate" minOccurs="0">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="effectiveDate" type="core:DateAndTime" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="updatedChangeNotes" minOccurs="0">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="changeNotes" type="core:OpaqueData" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="updatedChangeSource" minOccurs="0">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="changeSource" type="core:SourceReference" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
---End-Added--->
    </xs:sequence>
</xs:complexType>
```
