### ISSUE TITLE
OMG Issue 17435: String is a UML dataType and cannot be included as part of the model data types

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#113]
String cannot be defined as a data type, as it is already part of the UML core

http://www.omg.org/issues/cts2-ftf.html#Issue17435

**Comment by hsolbrig** [comment]
Pulled the String datatype out of the core module.   Still need to update the XMI to point String to the appropriate primitive type - it isn't obvious how to do this in the EA interface.

**Comment by kevinpeterson** [comment]
### Reason For Change

String is a UML dataType and cannot be included as part of the model data types. String cannot be defined as a data type, as it is already part of the UML core.

### Severity: Significant

### Proposed Resolution (PIM)

Remove the String datatype out of the core module.

Document:  Core.pdf
Page 4, remove text" String - a non-empty sequence of characters. As terminological resources are often multilingual, it is expected that most CTS2 Platform Specific Models (PSMs) will require that the String implementation support international character
sets."

![Figure 2.1: Data Types, Page 3.](http://informatics.mayo.edu/svn/trunk/cts2/spec/pim//images/DataTypes.png)

### Proposed Resolution (PSM)

N/A
