### ISSUE TITLE
OMG Issue 17436: Missing ValidationResponse class

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#115]
ValidationResponse was missing in final model.

http://www.omg.org/issues/cts2-ftf.html#Issue17436

**Comment by hsolbrig** [comment]
ValidationResponse had been defined in the REST and SOAP PSM but had not been pushed back to the PIM.  This was resolved by an update to the MiscInterface package in the Computational Model

**Comment by kevinpeterson** [comment]
### Reason For Change

ValidationResponse had been defined in the REST and SOAP PSM but had not been pushed back to the PIM.

### Severity: Significant

### Proposed Resolution (PIM)

Update to the MiscInterface package in the Computational Model to include ValidationResponse

Core.pdf
Added "Class ValidationResponse" after section 3.1.1.6.
![Figure 3.1.1.7: MiscInterface, Page 19.](http://informatics.mayo.edu/svn/trunk/cts2/spec/pim//images/MiscInterface.png)

3.1.1.7 Class ValidationResponse
The result of a change set validation call.
Attributes
• message - The output of the validation process
• validationStatus - an indicator whether the validation succeeded 

### Proposed Resolution (PSM)

N/A
