### ISSUE TITLE
OMG Issue 17437: Boolean is a UML data type and shouldn't be part of the model

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#116]
This is related to the string issue pointed out by Manfred.  Boolean cannot be defined as a data type, as it is already part of the UML core.

http://www.omg.org/issues/cts2-ftf.html#Issue17437

**Comment by craigstancl** [comment]
We've removed "Boolean" as a data type from the InterfaceTypes diagram.  References remain the same except they now point to a primitive type.

**Comment by kevinpeterson** [comment]
### Reason For Change

Boolean is a UML data type and shouldn't be part of the model.

### Severity: Significant

### Proposed Resolution (PIM)

Removed "Boolean" as a data type from the InterfaceTypes diagram.

Document: Core.pdf
![Figure 3.1.1.7: MiscInterface, Page 19.](http://informatics.mayo.edu/svn/trunk/cts2/spec/pim//images/MiscInterface.png)

### Proposed Resolution (PSM)

N/A
