### ISSUE TITLE
RTF Schema needs an official location

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#132]
The CTS2 Schema used in the RTF needs to have an official SVN (git?) location so developers can pull from it.  Right now it lives in http://informatics.mayo.edu/svn/trunk/cts2/spec/submission/OMGServerMap which is less than ideal

**Comment by kevinpeterson** [comment]
All specification artifacts are available in the GitHub repository https://github.com/cts2/cts2-specification.
