### ISSUE TITLE
OMG Issue 17078: Entity description services p20 typo

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#17]
http://www.omg.org/issues/cts2-ftf.html#Issue17078

Last line is "tetrieve"

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

### Proposed Resolution (PSM)

NA

#### Change Location: Entity Description Services, Page 20.

#### Description

Change text:

```
tetrieve an entity description ...
```

to:

```
retrieve an entity description ...
```
