### ISSUE TITLE
OMG Issue 17079: AssociationGraph p45 typo

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#18]
http://www.omg.org/issues/cts2-ftf.html#Issue17079

"To accomplish this, every EntityDescription ..." ->  EntitySynopsis

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

### Proposed Resolution (PSM)

NA

#### Change Location: Association Information Model, Page 45.

#### Description

Change text:

```
To accomplish this, every EntityDescription that occurs ...
```

to:

```
To accomplish this, every EntitySynopsis that occurs ...
```
