### ISSUE TITLE
OMG Issue 17087: ImplementationProfiles.ProfileElement not RESTful

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#26]
http://www.omg.org/issues/cts2-ftf.html#Issue17087

There is currently no way to get to each of the service implementations from the main page of the service.  The XML Schema for Profile Element needs to support (require?) a href for each of the profile element functions.  As an example, if a service supports SP_CODE_SYSTEM FP_READ, there should be a URL that links to the service implementation of CodeSystemCatalogEntryReadService

**Comment by kevinpeterson** [comment]
### Reason For Change

There is currently no way to get to each of the service implementations from the main page of the service. The XML Schema for Profile Element needs to support (require?) a href for each of the profile element functions. As an example, if a service supports SP_CODE_SYSTEM FP_READ, there should be a URL that links to the service implementation of CodeSystemCatalogEntryReadService.

### Severity: Minor

### Proposed Resolution (PIM)

NA

### Proposed Resolution (PSM)

Add a 'FunctionalProfileEntry' type with an 'href' attribute so that Service pages can be linked.

#### Change Location: CoreService.xsd

#### Description

Create an new type 'FunctionalProfileEntry' and associated it to 'ProfileElement' as shown below.

#### Updated XML

``` xml
<xs:complexType name="ProfileElement">
    <xs:sequence>
        <xs:element name="structuralProfile" type="StructuralProfile" minOccurs="1" maxOccurs="1">
            <xs:annotation>
                <xs:documentation>A resource that is implemented by a service instance</xs:documentation>
            </xs:annotation>
        </xs:element>
        <xs:element name="functionalProfile"  type="FunctionalProfileEntry" minOccurs="1" maxOccurs="unbounded">
            <xs:annotation>
                <xs:documentation>A functional profile that the service instance supports for the corresponding structure</xs:documentation>
                <xs:appinfo>PSM</xs:appinfo>
            </xs:annotation>
        </xs:element>
    </xs:sequence>
</xs:complexType>
```

``` xml
<xs:complexType name="FunctionalProfileEntry">
    <xs:annotation>
        <xs:documentation>The combination of a <b>FunctionalProfile</b> and a link to the service description that describes the function/structure</xs:documentation>
        <xs:appinfo>PSM</xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
        <xs:extension base="FunctionalProfile">
            <xs:attribute name="href" type="core:ServiceURI" use="optional">
                <xs:annotation>
                    <xs:documentation>A link to the service description for this particular function. The href must reference an instance of <b>BaseService</b></xs:documentation>
                    <xs:appinfo>PSM</xs:appinfo>
                </xs:annotation>
            </xs:attribute>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

```

**Comment by kevinpeterson** [comment]
Upon implementation, there seem to be a few problems with the above resolution.
- A ProfileElement does not necessarily have a "StructuralProfile" - Import/Export for example.
- This allows for multiple 'FunctionalProfile's, but there is only one 'href' -- if there are multiple FunctionalProfiles, multiple hrefs would be needed.

**Comment by kevinpeterson** [comment]
I believe it would make sense to have 'ProfileElement' represented this way:

``` xml
<xs:complexType name="ProfileElement">
    <xs:sequence>
        <xs:element name="functionalProfile" type="FunctionalProfile"/>
        <xs:element name="structuralProfile" type="StructuralProfile" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="href" type="core:RenderingURI" use="optional">
        <xs:annotation>
            <xs:documentation>a <i>RenderingURI</i> that, when dereferenced, results in a CTS<sub>2</sub> compliant representation of the meaning of the given <i>NameAndMeaningReference</i>. This must be present if the
                            implementing CTS<sub>2</sub> service is aware of a CTS<sub>2</sub> resource that carries the definition. </xs:documentation>
        </xs:annotation>
    </xs:attribute>
</xs:complexType>
```

A Single 'FunctionalProfile' is paired with an optional 'StructuralProfile', with an 'href.'

**Comment by hsolbrig** [comment]
Note 1:  The documentation in the href definitely needs revision.  Will propose below.
Note 2:  I would argue that even for generic services IMPORT/EXPORT/UPDATE, it is still important for the service to identify what sort of resources it will and won't process.  I would argue in favor of returning to the original model in the specification, with a single structural profile (e.g. SP_CODE_SYSTEM, SP_CODE_SYSTEM_VERSION, etc) accompanied by a set of one or more functional profiles (FP_READ, FP_IMPORT, FP_UPDATE, etc.)   and then putting a href onto each functional profile.  The href would take you to the appropriate SP/FP entry.  (e.g. CodeSystemReadService, CodeSystemUpdateService, etc.).  

This leaves us with a couple of interesting questions, however:
1) Can a service merge the various Functional Profiles into a single resource?  (e.g. CodeSystemService, which contains all of the information for Read, Update, Query, etc.)  Is there ever any reason that a service would not want to (in that, should it be mandatory in the REST PSM)
2) How do we represent the individual functions?  Once I get to the CodeSystemReadService page, what should a link to the exists and read URL's look like?

**Comment by kevinpeterson** [comment]
Yes, this makes sense. As long as we assign everything a structural profile, it will work - and I think that is a valid thing to do, as you said.

1) I think that's reasonable to combine Functional Profiles. I can't think of a reasonable reason why they need to be separated.
2) ... also things like maintenance (DELETES, PUTS, POSTS). How do we (or can we) represent a non-GET function with an 'href'? I'm not sure.

**Comment by hsolbrig** [comment]
Committed changes as SVN 6547.   At the moment, the functional href is optional, but we might want to consider strengthening it.  We also need to see whether this requires a change in the PIM.

Wrt question 2)  - this seems like an opportunity to parse the WADL into forms?
