### ISSUE TITLE
OMG Issue 17088: Documentation issue on ProfileElement

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#27]
http://www.omg.org/issues/cts2-ftf.html#Issue17088

The documentation for ProfileElement in CoreService.xsd is not correct.  Need to chase this back to its source and fix it.

**Comment by kevinpeterson** [comment]
I couldn't find any documentation of 'ProfileElement' in the specification PDFs.

**Comment by hsolbrig** [comment]
It is actually on page 3 of the first document, and currently says "ProfileElement appears in service implementations, once per structural profile that is supported by the implementation instance.  Each occurrence records the set of functional profiles that are supported for the specific structural profile".   

This should be injected automatically once we get the rest of the UML worked out.

**Comment by kevinpeterson** [comment]
### Reason For Change

The documentation for ProfileElement in CoreService.xsd is missing.

### Severity: Support Text

### Proposed Resolution (PIM)

N/A

### Proposed Resolution (PSM)

#### Change Location: CoreService.xsd

#### Description

Add the following documentation to the 'ProfileElement' type:

``` xml
ProfileElement appears in service implementations, once per structural profile that is supported by the implementation instance. Each occurrence records the set of functional profiles that are supported for the specific structural profile
```

#### Updated XML

``` xml
<xs:complexType name="ProfileElement">
---Start-Added--->
    <xs:annotation>
        <xs:documentation>ProfileElement appears in service implementations, once per structural profile that is supported by the implementation instance. Each occurrence records the set of functional profiles that are supported for the specific structural profile</xs:documentation>
    </xs:annotation>
---End-Added--->
    <xs:sequence>
        <xs:element name="structuralProfile" type="StructuralProfile" minOccurs="1" maxOccurs="1">
            <xs:annotation>
                <xs:documentation>A resource that is implemented by a service instance</xs:documentation>
            </xs:annotation>
        </xs:element>
        <xs:element name="functionalProfile"  type="FunctionalProfileEntry" minOccurs="1" maxOccurs="unbounded">
            <xs:annotation>
                <xs:documentation>A functional profile that the service instance supports for the corresponding structure</xs:documentation>
                <xs:appinfo>PSM</xs:appinfo>
            </xs:annotation>
        </xs:element>
    </xs:sequence>
</xs:complexType>
```
