### ISSUE TITLE
OMG Issue 17107: Remove CONCEPT_DOMAIN_BINDING from ReferenceType

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#29]
http://www.omg.org/issues/cts2-ftf.html#Issue17107

Concept Domain Bindings are not referenced anywhere in the specification and the entry needs to be removed from the ReferenceType model

**Comment by kevinpeterson** [comment]
### Reason For Change

Concept Domain Bindings are not referenced anywhere in the specification and the entry needs to be removed from the ReferenceType model.

### Severity: Minor

### Proposed Resolution (PIM)

Updated Diagram (Figure 2.4: Reference Types. Core, Page 10.)
![Figure 2.4: Reference Types. Core, Page 10.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/04/ReferenceType.jpg)

### Proposed Resolution (PSM)

N/A
