### ISSUE TITLE
OMG Issue 17108: EntityReferences - URIAndEntityNameList

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#30]
http://www.omg.org/issues/cts2-ftf.html#Issue17108

Need to check whether this is used anywhere in the spec and pull it if not.

**Comment by kevinpeterson** [comment]
I didn't find URIAndEntityNameList in any schemas.

**Comment by kevinpeterson** [comment]
### Reason For Change

'URIAndEntityNameList' is not used in the specification and should be removed

### Severity: Minor

### Proposed Resolution (PIM)

On page 19 of Core, remove 'Class URIAndEntityNameList.'

Updated Diagram (Figure 2.7: Entity Reference. Core, Page 16.)
![Figure 2.7: Entity Reference. Core, Page 16.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/04/EntityReference.jpg)

### Proposed Resolution (PSM)

N/A
