### ISSUE TITLE
OMG Issue 17109: Changeable changeDescription cardinality constraint

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#31]
http://www.omg.org/issues/cts2-ftf.html#Issue17109

Need to add an invariant to Changeable indicating that the changeDescription cardinality must be 1..1 if the profile supports HISTORY or MAINTENANCE

**Comment by kevinpeterson** [comment]
### Reason For Change

Missing invariant in PIM for 'Changeable'

### Severity:  Support Text

### Proposed Resolution (PIM)

Update PIM text

### Proposed Resolution (PSM)

NA

#### Change Location: Core Information Model, Page 32.

#### Description

Add the following text under 'Class Changeable':

```
Invariants:
1. changeDescription must be present if the profile supports HISTORY or MAINTENANCE
```
