### ISSUE TITLE
OMG Issue 17113: Typo on page 3 of Statement Information model

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#35]
http://www.omg.org/issues/cts2-ftf.html#Issue17113

subject - ahe subject
              ____

**Comment by cts2** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

### Proposed Resolution (PSM)

NA

#### Change Location: Statement Information Model, Page 3.

#### Description

Change text:

```
subject - ahe subject
```

to:

```
subject - the subject
```
