### ISSUE TITLE
OMG Issue 17114: Typo on page 11 of statement information model

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#36]
http://www.omg.org/issues/cts2-ftf.html#Issue17114

blank exceptions entry

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

### Proposed Resolution (PSM)

NA

#### Change Location: Statement Information Model, Page 11.

#### Description

The blank exception in the 'StatementDirectoryURI' type should be removed.
