### ISSUE TITLE
OMG Issue 17117: ResolvedValueSetDirectory misnamed and mistyped

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#39]
http://www.omg.org/issues/cts2-ftf.html#Issue17117

ResolvedValueSetDirectory is the return type of the "resolve" function for ValueSetDefinitionResolution, which should return a ResolvedValueSetHeader as part of the directory and an iteratable EntitySynopsis list.  Both the name and model of this particular return type need to be fixed.  This change applies to the UML and spec, the XML Schema and the WSDL/WADL

**Comment by kevinpeterson** [comment]
I think it makes sense to have an object called "ResolvedValueSetDirectory" that is a directory of all "ResolvedValueSets" on the system. This "ResolvedValueSetDirectory" would contain summaries of the available "ResolvedValueSets" - these summaries would basically be the "ResolvedValueSetHeader" -- telling what it was resolved against, etc.

Then, getting to the question above, we do need a way to iterate a "ResolvedValueSet." Something like an "IterableResolvedValueSet" (to follow the ChangeSet pattern) or similar, which has properties as described in Harold's comment above.

**Comment by kevinpeterson** [comment]
### Reason For Change

'ResolvedValueSet' is not iterable. It must be accessed as a whole, which will be problematic and will not scale to large entries. This needs to follow the same pattern as 'ChangeSet', where there is a 'complete' version and an 'iterable' version.

### Severity: Significant

### Proposed Resolution (PIM)

TODO:

Updated Diagram (Figure 3.4: Resolved ValueSet. ValueSetDefinition, Page 27.)
![Figure 3.4: Resolved ValueSet. ValueSetDefinition, Page 27.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/05/ResolvedValueSet.png)

### Proposed Resolution (PSM)

#### Change Location: ValueSetDefinition.xsd

#### Description

Add the type 'IteratableResolvedValueSet' to allow for iterable access of a 'ResolvedValueSet'.

#### Updated XML

``` xml
<xs:element name="IteratableResolvedValueSet">
    <xs:annotation>
        <xs:documentation>A ResolvedValueSet whose contents are available as a set of directory entries that allows iteration.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:complexContent>
            <xs:extension base="core:Directory">
                <xs:sequence>
                    <xs:element name="resolutionInfo" type="ResolvedValueSetHeader" minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>the set of parameters that were used in the resolution of this set. <i>resolutionInfo</i> provides all the information necessary to recreate the actual <i>resolution</i> when presented to a
                                        CTS<sub>2</sub> service instance that contains all of the necessary definitions and code system versions.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="entry" type="core:EntitySynopsis" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation>a synopsis of the <i>EntityDescription</i> that has been determined to be a member of the value set named in <i>resolutionInfo</i> according to the stated criteria or "bindings"</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:element>
```
