### ISSUE TITLE
Alignment definitions “Associations” and “Mapping” with the HL7 CTS2 SFM

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#65]
The DSTU HL7 CTS2 considers that the "Mapping" is done through Associations (inter-code system associations).  Associations define the relationships or linkages between concepts or associations....and provide a set of functionality that provides the ability to map concepts and the concept's associated attributes from a source terminology to a concept in a target terminology, or create relationships between concepts within a single code system.» 

PIM:  ASSOCIATION is a formal “semantic” assertion about a named entity, in the form of subject, predicated and object including any provenance, qualifiers, or internal BNODEs and MAP is set of rules that associate a set of entity references from one domain into those in another.  

The difference in definitions can lead to confusion.  Proposition:  explain the rationale for the different definitions and then either include this definition in the HL7 CTS2 or the PIM considers it as "out of scope" (align the definitions).

**Comment by hsolbrig** [comment]
The mapping model in the CTS2 specification derives from three sources:

<ol>
<li>The SNOMED-CT RF2 Simple and Complex Map Refset definitions</li>
<li>The MRMAP resource defined in the UMLS</li>
<li>The terminology map model included in the GEM resource</li>
</ol> 


To the best of our knowledge, the resulting model is a super set of the model in the HL7 DSTU, but includes many to many maps, rules, the notion of "does not map" (vs. has not been considered, etc).  

When it comes to the definition of "Association", definition is drawn from a different glossary.  Will attempt to clarify

**Comment by aestelrich** [comment]
In the clarification could you please explain how does the model cover the following use cases:
1.  The Code Systems in HL7 have a hierarchy which is expressed by Associations in the SFM (parent-child relationship).  How is this done in the PIM?
2.  How would you map a code from the MaterialKind code (from a code system such as ATC) onto a Product code (see diagram in the Common Product Model).  In this case, what would the AssociationType be called?   We think the AssociationType should be coded using the codes as present in the SpecializedKind role.  We can use an example that we have at Phast – a medical device (Product) can be either described using the Cladimed Code System (therapeutical classes) or LPP (for billing).
