### ISSUE TITLE
Optional attribute Code System OID

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#68]
In the description of the Code System Catalog Entry the identification is done via the Code System name:  "codeSystemName - the local identifier that uniquely identifies the code system within the context of the implementing service. Note that the about URI is the globally unique identifier."  

The HL7 culture is used to manage messages and documents via OIDs.  An optional attribute:  CodeSystemOID should perhaps be available.  If not, a paragraph describing how the relationship is managed between URI and OIDs within the usage that HL7 is expecting of a terminology service.

**Comment by hsolbrig** [comment]
Good point.  We had originally had OID examples throughout the document (e.g. urn:oid:2.16.840.1.113883.6.96), but when we discovered that HL7 had not established a mechanism for identifying <i>versions</i> using OIDs and had no sanctioned way to combine a concept code and an OID, we de-emphasized the OIDs as their use was very limited.  Will include an explanation of how one turns an OID into a URN where it is appropriate.

**Comment by aestelrich** [comment]
We are not asking for an explanation of how one turns an OID into a URN.   We are asking for an optional additional attribute especially dedicated to OID.  The URN is needed for a REST-oriented model.  

Use case:  certain code system have legitimately several official terminology providers (or sources of truth) such as LOINC which has Rengenstrief Institute for the universal version and ASIP Santé for the French translations and extensions, so there are distinct URLs while there is only one LOINC OID.
