### ISSUE TITLE
OMG Issue 17331:  section  1.1.2.1 Class CodeSystemCatalogEntryDirectory typo

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#69]
http://www.omg.org/issues/cts2-ftf.open.html#Issue17331

In the pdf2 in section  1.1.2.1 Class CodeSystemCatalogEntryDirectory we think this is a typo and it should be CodeSystemDirectory.

**Comment by kevinpeterson** [comment]
It is called a 'CodeSystemCatalogEntryDirectory' to indicate that it is a Directory of 'CodeSystemCatalogEntry's - and to be consistent with the Directory naming conventions of the spec.

**Comment by kevinpeterson** [comment]
### Reason For Change

N\A - No Change Necessary

### Severity: NONE

### Proposed Resolution (PIM)

N\A
After review, the existing text is correct, and the change should not be applied to the PIM.

### Proposed Resolution (PSM)

N\A
