### ISSUE TITLE
Exclude UnsupportedLanguage from the exception criteria

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#70]
In the service CodeSystemCatalogReadService, for example, we have listed as an exception for the exist operation the UnsupportedLanguage - The referenceLanguage is not supported by the service.  If the Code System is multilingual, instead of getting the information in the original language, there will be an error message.  Proposition:  Exclude UnsupportedLanguage from the exception criteria so that multilingual Code Systems are supported.  Our CTS2 implementation STS has a parameter, PreferredLanguage, indicating the preference of the language (if the information is present in French, it will be obtained in French, if it is not available in French but only in English, then it will be obtained in English).

**Comment by hsolbrig** [comment]
The service can decide whether it supports French of not.  If a service provider believes that English is an acceptable substitute for French, they are free to respond in English.   This exception exists, however, for cases where this is not the case.

**Comment by aestelrich** [comment]
Ok.  Issue closed.
