### ISSUE TITLE
OMG Issue 17330:  Concept Domain Catalog Query Service missing description 

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#75]
http://www.omg.org/issues/cts2-ftf.open.html#Issue17330

11-09-03 CTS2 Concept Domain and Concept Domain Binding Services

In section 2.2 Concept Domain Catalog Query Service the section goes onto describing Concept Domain Catalog History.  Is is possible that the Query service description (resolve and resolveAsList) were missed due to a cut and paste error?

**Comment by kevinpeterson** [comment]
I am unable to find the described error.

**Comment by kevinpeterson** [comment]
### Reason For Change

N/A

### Reason For No Change

Upon further discussion, the existing PIM text is correct and change is not needed.

### Severity: None

### Proposed Resolution (PIM)

N/A

### Proposed Resolution (PSM)

N/A
