### ISSUE TITLE
Managing codes in a Code System via Code System Versions

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#77]
« The Code SystemCatalogEntry model carries metadata about the code system itself, while CodeSystemVersionCatalogEntry carries information about the content of a code system. ».

In the HL7 CTS2 standard, a code or a concept is directly part of a Code System, and can or cannot be present in various versions of the Code Systems.  This is much more representative of the real life and much more adaptable.

**Comment by hsolbrig** [comment]
The OMG CTS2 standard does not make any "part of" assertions between EntityDescription and CodeSystem.  A particular version of a code system may or may not describe an entity.  I'm not sure what is intended by the phrase "real life", but it would be quite strange to have descriptions that can never change - even if this were the case, wouldn't it be identified by saying "There is only one version of (strange) code system X"?

**Comment by aestelrich** [comment]
Our comment was not about an entity that never changes but about the efficient support of the coded concepts that may have not been modified from one version to another.
