### ISSUE TITLE
OMG Issue 17327:  Service map catalog typo

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#78]
http://www.omg.org/issues/cts2-ftf.open.html#Issue17327

11-09-08 Value Set services - The ValueSetCatalogReadService provides direct access to the service map catalog. Typo - Value Set Catalog instead of service map catalog.

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

### Proposed Resolution (PSM)

NA

#### Change Location: Value Set Services, Page 6.

#### Description

Change text:

```
The ValueSetCatalogReadService provides direct access to the service map catalog. ...
```

to:

```
The ValueSetCatalogReadService provides direct access to the service value set catalog. ...
```
