### ISSUE TITLE
Multiple object instantiations in order to support multilingual terminological resources

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#79]
It seems that the Axiomatic Datatypes were used rather then the ISO20190 datatypes.  The ISO20190 ST datatype allows for the attribute "language", which in turn allows to indicate the language of a string.  If the ST datatype is not implemented, in order to claim multilingual conformance, multiple instantiations of an object containing attributes such as  "description", "provenanceDetails", "administrativeInfo" is needed .  Secondly, if the ST datatypes were to be implemented, this would allow for the attribute "translation" (which is found in the ST datatype attributes) to be present just once.  This in turns allows the possibility of having an original description as well as the possibility to have as many  translations as available per object instance.  If the ST datatype is not present this will also need multiple object instantiations in order to support international terminological resources.

**Comment by hsolbrig** [comment]
CTS2 deliberately used a minimal set of data types, which allows them to be implemented in a variety of ways including XML Schema, plain old Java, RDF and OWL, ISO 21090, etc.   The need for multiple instantiations of a string are quite deliberate as the provenance and administration of different languages are rarely identical.  As an example, the UK is responsible for the English components of SNOMED CT, Argentina for the Spanish, etc.  Even "translation" has nuances - is it a literal translation, a human guided translation, etc.   The ST datatype embodies a subset of these needs, but it is explicit in the CTS2 model.  Not sure what is meant by "multiple object instantiations", however, as (hopefully) the CTS2 specification is not about objects, period.

**Comment by aestelrich** [comment]
Ok, accepted, issue closed.
