### ISSUE TITLE
OMG Issue 17071: AnonymousStatement typo

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#8]
http://www.omg.org/issues/cts2-ftf.html#Issue17071

StatmentQualifier -> statementQualifier

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM diagram

### Proposed Resolution (PSM)

NA

#### Change Location: Statement Information Model, Page 3.

#### Description

In the 'classStatement' diagram in 'AnonymousStatement'
Change text:

```
statmentQualifier
```

to:

```
statementQualifier
```
