### ISSUE TITLE
OMG Issue 17325:  ConceptDomainBindingReadService QueryControl parameters

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#81]
http://www.omg.org/issues/cts2-ftf.open.html#Issue17325

The QueryControl parameter was omitted from the read and readByURI operations in ConceptDomainBindingService.

**Comment by kevinpeterson** [comment]
### Reason For Change

The QueryControl parameter was omitted from the read and readByURI operations in ConceptDomainBindingService.

### Severity: Minor

### Proposed Resolution (PIM)

In the ConceptDomainBindingService - methods 'read' and 'readByUri', add a parameter 'queryControl of type 'AssociationDirectoryURI.'

Updated Diagram (Figure 4.1: Concept Domain Binding Read. Concept Domain Binding, Page 20.)
![Figure 4.1: Concept Domain Binding Read. Concept Domain Binding, Page 20.](http://informatics.mayo.edu/svn/trunk/cts2/spec/pim//images/ConceptDomainCatalogRead.png)

### Proposed Resolution (PSM)

In the ConceptDomainBindingReadServiceTypes.xsd - methods 'read' and 'readByUri', add a parameter 'queryControl of type 'AssociationDirectoryURI.'

#### Change Location: ConceptDomainBindingReadServiceTypes.xsd

#### Description

Add in the following element to types 'read' and 'readByURI':

``` xml
<xs:element minOccurs="0" name="queryControl" type="coreService:QueryControl" />
```

### Updated XML

``` xml
<xs:element name="readByURI" type="tns:readByURI"/>
  <xs:complexType name="readByURI">
    <xs:sequence>
      <xs:element minOccurs="1" name="uri" type="core:DocumentURI"/>
---Added---> <xs:element minOccurs="0" name="queryControl" type="coreService:QueryControl" />
    </xs:sequence>
</xs:complexType>
```

``` xml
<xs:element name="read" type="tns:read"/>
<xs:complexType name="read">
    <xs:sequence>
      <xs:element minOccurs="1" name="conceptDomain" type="coreService:NameOrURI"/>
      <xs:element minOccurs="1" name="valueSet" type="coreService:NameOrURI"/>
      <xs:element minOccurs="0" name="applicableContext" type="coreService:NameOrURI"/>
      <xs:element minOccurs="0" name="bindingQualifier" type="coreService:NameOrURI"/>
---Added---> <xs:element minOccurs="0" name="queryControl" type="coreService:QueryControl" />
    </xs:sequence>
</xs:complexType>
```
