### ISSUE TITLE
OMG Issue 17320:  Inconsistent element/complexType declarations

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#88]
http://www.omg.org/issues/cts2-ftf.open.html#Issue17320

The current xml schemas in the rest/schema directory present an inconsistent combination of the "Venetian Blind" and "Garden of Eden" schema patterns (http://developers.sun.com/jsenterprise/archive/nb_enterprise_pack/reference/techart/design_patterns.html), where all elements except the elemMsg, elemList and elemDirectory have both complexType and element declarations.   The approaches to these two patterns can be quite different in a schema compiler such as pyxb.  We propose that _all_ element declarations follow the general pattern:

``` xml
<xs:element name='x' type = 'x'/>
<xs:complexType name='x'>
    ...
</xs:complexType>
```

For resources that can be document level elements and complex (or simple) for the rest)

**Comment by kevinpeterson** [comment]
### Reason For Change

The current xml schemas in the rest/schema directory present an inconsistent combination of the "Venetian Blind" and "Garden of Eden" schema patterns (http://developers.sun.com/jsenterprise/archive/nb_enterprise_pack/reference/techart/design_patterns.html), where all elements except the elemMsg, elemList and elemDirectory have both complexType and element declarations.   The approaches to these two patterns can be quite different in a schema compiler such as pyxb.  We propose that _all_ element declarations follow the general pattern:

``` xml
<xs:element name='x' type = 'x'/>
<xs:complexType name='x'>
    ...
</xs:complexType>
```

For resources that can be document level elements and complex (or simple) for the rest)

### Severity: Minor

### Proposed Resolution (PIM)

N/A

### Proposed Resolution (PSM)

#### Change Location: All XSDs

#### Description

Changed any XSD Element in the form of:

``` xml
<xs:element name='x'>
   <xs:complexType>
   ...
   </xs:complexType>
</xs:element>
```

to:

``` xml
<xs:element name='x' type = 'x'/>
   <xs:complexType name='x'>
    ...
</xs:complexType>
```
