### ISSUE TITLE
OMG Issue 17072: ChangeDescription stereotypes

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#9]
http://www.omg.org/issues/cts2-ftf.html#Issue17072

ChangeType, committed, containingChangeSet, prevChangeSet, changeDate and clonedResource should be ReadOnly

**Comment by kevinpeterson** [comment]
### Reason For Change

ChangeType, committed, containingChangeSet, prevChangeSet, changeDate and clonedResource should be ReadOnly

### Severity: Minor

### Proposed Resolution (PIM)

Updated Diagram (Figure 2.12: CTS2 Change Model. Core, Page 30.)
![Figure 2.12: CTS2 Change Model. Core, Page 30.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/04/Updates.jpg)

### Proposed Resolution (PSM)

N/A
