### ISSUE TITLE
OMG Issue 17350:  Missing documentation on StatementSubject

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#92]
http://www.omg.org/issues/cts2-ftf.html#Issue17350

subjectType is not documented on page 3 of the Statement Information Model

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation. Missing documentation on StatementSubject.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

#### Change Location: Statement, Page 3.

#### Description

Add the following documentation for the 'subjectType' attribute of the 'StatementSubject' class:

```
A discriminant that determines the statement subject type. PSM's that support string typing systems may implement this through the built-in-type system rather than providing a specific element.
```

### Proposed Resolution (PSM)

NA
