### ISSUE TITLE
OMG Issue 17353:  Exception listed twice in EntityDescriptionQueryService

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#95]
http://www.omg.org/issues/cts2-ftf.html#Issue17353

restrictToCodeSystem lists InvalidDirectoryType twice in the exception list.

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation. Method 'restrictToCodeSystem' in EntityDescriptionQueryService lists InvalidDirectoryType twice in the exception list.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM text

#### Change Location: Entity Description, Page 24.

#### Description

Remove one of the duplicate 'InvalidDirectoryType' exceptions from the 'InvalidDirectoryType' method.

### Proposed Resolution (PSM)

NA
